apiVersion: v1
kind: Service
metadata:
    name: toto-nodems-diet-svc
spec:
    selector:
        microservice: toto-nodems-diet
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
         
